openapi: 3.0.3
info:
  title: Coolblue test task
  version: 1.0.0
  description: API for solving Traveling Salesperson Problem
paths:
  /solve/:
    post:
      operationId: solve_create
      description: Launces calculation task with given parameters, returns task id
        for retrieving
      tags:
      - solve
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /solve/{id}/:
    get:
      operationId: solve_retrieve
      description: Retrieves task result by id
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - solve
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
